/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as books from "../books.js";
import type * as books_preprocessing from "../books_preprocessing.js";
import type * as books_preprocessing_test from "../books_preprocessing_test.js";
import type * as books_test from "../books_test.js";
import type * as processImage from "../processImage.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  books: typeof books;
  books_preprocessing: typeof books_preprocessing;
  books_preprocessing_test: typeof books_preprocessing_test;
  books_test: typeof books_test;
  processImage: typeof processImage;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
